server.port=8080
spring.application.name=mediaLaboSolutionsGateway

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG
