spring.application.name=mediaLaboSolutionsMicroMongoDB

server.port=8082

spring.data.mongodb.uri=mongodb+srv://david_db_user:V0YLGv0vCe9CaLhK@cluster0.ey05tit.mongodb.net/?appName=Cluster0
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=USER

