spring.application.name=mediaLaboSolutionsMicroMongoDB

server.port=8082

spring.data.mongodb.uri=${MONGODB_URI}
spring.security.user.name=${APP_USER}
spring.security.user.password=${APP_PASSWORD}
spring.security.user.roles=${APP_ROLE}
